config/routes.rb
Rails.application.routes.draw do

  resources :assistants
  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assistant.rb
class Assistant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/assistants_controller.rb
class AssistantsController < ApplicationController
  before_action :set_assistant, only: [:show, :edit, :update, :destroy]

  # GET /assistants
  # GET /assistants.json
  def index
    @assistants = Assistant.all
  end

  # GET /assistants/1
  # GET /assistants/1.json
  def show
  end

  # GET /assistants/new
  def new
    @assistant = Assistant.new
  end

  # GET /assistants/1/edit
  def edit
  end

  # POST /assistants
  # POST /assistants.json
  def create
    @assistant = Assistant.new(assistant_params)

    respond_to do |format|
      if @assistant.save
        format.html { redirect_to @assistant, notice: 'Assistant was successfully created.' }
        format.json { render :show, status: :created, location: @assistant }
      else
        format.html { render :new }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assistants/1
  # PATCH/PUT /assistants/1.json
  def update
    respond_to do |format|
      if @assistant.update(assistant_params)
        format.html { redirect_to @assistant, notice: 'Assistant was successfully updated.' }
        format.json { render :show, status: :ok, location: @assistant }
      else
        format.html { render :edit }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assistants/1
  # DELETE /assistants/1.json
  def destroy
    @assistant.destroy
    respond_to do |format|
      format.html { redirect_to assistants_url, notice: 'Assistant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assistant
      @assistant = Assistant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assistant_params
      params.require(:assistant).permit(:name, :email, :password, :website, :other, :about)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistants_helper.rb
module AssistantsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/assistants/_form.html.erb
<%= form_with(model: assistant, local: true) do |form| %>
  <% if assistant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assistant.errors.count, "error") %> prohibited this assistant from being saved:</h2>

      <ul>
      <% assistant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :assistant_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :assistant_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :assistant_password %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :assistant_website %>
  </div>

  <div class="field">
    <%= form.label :other %>
    <%= form.text_area :other, id: :assistant_other %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about, id: :assistant_about %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assistants/edit.html.erb
<h1>Editing Assistant</h1>

<%= render 'form', assistant: @assistant %>

<%= link_to 'Show', @assistant %> |
<%= link_to 'Back', assistants_path %>

app/views/assistants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assistants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Website</th>
      <th>Other</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assistants.each do |assistant| %>
      <tr>
        <td><%= assistant.name %></td>
        <td><%= assistant.email %></td>
        <td><%= assistant.password %></td>
        <td><%= assistant.website %></td>
        <td><%= assistant.other %></td>
        <td><%= assistant.about %></td>
        <td><%= link_to 'Show', assistant %></td>
        <td><%= link_to 'Edit', edit_assistant_path(assistant) %></td>
        <td><%= link_to 'Destroy', assistant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assistant', new_assistant_path %>

app/views/assistants/new.html.erb
<h1>New Assistant</h1>

<%= render 'form', assistant: @assistant %>

<%= link_to 'Back', assistants_path %>

app/views/assistants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assistant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @assistant.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @assistant.password %>
</p>

<p>
  <strong>Website:</strong>
  <%= @assistant.website %>
</p>

<p>
  <strong>Other:</strong>
  <%= @assistant.other %>
</p>

<p>
  <strong>About:</strong>
  <%= @assistant.about %>
</p>

<%= link_to 'Edit', edit_assistant_path(@assistant) %> |
<%= link_to 'Back', assistants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vapool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1> Welcome to VA Pool </h1>